spring.application.name=Tp2jeePart2

# 1. Dit à Spring d'utiliser H2 (La base relationnelle)
spring.datasource.url=jdbc:h2:mem:Tp2jeePart2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# 2. Active la console H2 pour que tu puisses voir tes tables
# Adresse : http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Hibernate (JPA) crée les tables automatiquement à partir de tes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect