spring.application.name=BiblioTechProject

# Utilisation de H2 (Base SQL en mémoire pour les tests)
spring.datasource.url=jdbc:h2:mem:bibliotechdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Pour voir les tables dans ton navigateur : http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Création automatique des tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true