spring.application.name=BiblioTechRelational

# 1. Connexion à la base SQL H2 (En mémoire)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 2. Accès à l'interface visuelle (Console H2)
# Adresse : http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Hibernate : Création automatique des tables à partir de ton code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true